# these are the basic settings
# the MUST be there
do_text = true
do_grep = true
do_glyph = true
do_object = false
do_all_docs = true
selection_mode = true
# now the file names
# they have to be in one line
# the toml specs say you can break lines in arrays
# but the toml.js does not allow that at the moment
[text]
files = ["my_first_text_find_and_change","another one"]
[grep]
files = ["somegrepsearch", "find tabs", "something else"]
[glyph]
files = []
[objects]
files = []