# these are the basic settings
# the MUST be there
do_text = true
do_grep = true
do_glyph = true
do_object = false
do_all_docs = true
# now the file names
# they have to be in one line
# the toml specs say you can break lines in arrays
# but the toml.js does not allow that at the moment
[text]
files = ["bfnr_text_1","bfnr_text_2"]
[grep]
files = ["bfnr_test1", "bfnr_test2", "bfnr_test3"]
[glyph]
files = []
[objects]
files = []